### ISSUE TITLE
mambabuild fails with Problem: nothing provides requested openssl 1.1.1

### ISSUE THREAD

**Issue by chrisburr** [mamba-org/boa#119]
## Versions

```bash
$ conda list | rg '(conda-build|boa|mamba|conda )' | sort -u
boa                       0.3.5            py37h89c1867_0    conda-forge
conda                     4.9.2            py37h89c1867_0    conda-forge
conda-build               3.21.4           py37h89c1867_0    conda-forge
mamba                     0.7.14           py37h7f483ca_0    conda-forge
micromamba                0.7.14               he9b6cbd_0    conda-forge
```

## Reproducer

```bash
git clone git@github.com:conda-forge/srm-ifce-feedstock.git
cd srm-ifce-feedstock
git checkout 433f550a
conda mambabuild -m .ci_support/linux_64_.yaml recipe
```

## Output

```log
Updating build index: /home/cburr/miniconda3/conda-bld

No numpy version specified in conda_build_config.yaml.  Falling back to default numpy value of 1.16
WARNING:conda_build.metadata:No numpy version specified in conda_build_config.yaml.  Falling back to default numpy value of 1.16
Adding in variants from internal_defaults
INFO:conda_build.variants:Adding in variants from internal_defaults
Adding in variants from /home/cburr/Development/conda-forge/srm-ifce-feedstock/.ci_support/linux_64_.yaml
INFO:conda_build.variants:Adding in variants from /home/cburr/Development/conda-forge/srm-ifce-feedstock/.ci_support/linux_64_.yaml
Attempting to finalize metadata for srm-ifce
INFO:conda_build.metadata:Attempting to finalize metadata for srm-ifce
conda-forge/linux-64     Using cache
conda-forge/noarch       Using cache
pkgs/main/linux-64       [====================] (00m:00s) No change
pkgs/main/noarch         [====================] (00m:00s) No change
pkgs/r/linux-64          [====================] (00m:00s) No change
pkgs/r/noarch            [====================] (00m:00s) No change
home/cburr/miniconda3/co [====================] (00m:00s) Done
home/cburr/miniconda3/co [====================] (00m:00s) Done
Mamba failed to solve:
 - openssl
 - gsoap 2.8.106.*
 - glib
 - openssl 1.1.1
 - cgsi-gsoap
 - gct
 - glib 2.*

with channels:

The reported errors are:
⇟   Encountered problems while solving.
   Problem: nothing provides requested openssl 1.1.1

```

**Comment by wolfv** [comment]
argh, the problem is that there is no `*` at the end of the openssl version specification :/

**Comment by wolfv** [comment]
because the openssl version is `1.1.1g` or something like that. 

so basically, mamba is more strict here than it should be. on the other hand, there is some room for interpretation with this pin IMO.

**Comment by chrisburr** [comment]
Yeah, I'm looking forward to OpenSSL 3: https://wiki.openssl.org/index.php/OpenSSL_3.0#Versioning_Scheme

Personally I'm happy to just fix it in the global conda-forge pinning if it's otherwise harmless?

**Comment by wolfv** [comment]
one potential drawback would be if 1.1.12 would be released, i am not sure what would happen then

**Comment by wolfv** [comment]
@chrisburr have you gotten around to fix this in the pinnings of conda-forge? if not, we can just apply a "loosen-spec" inside the solver.py here.

To be honest, conda behaves quite differently with regards to this loosen spec. I had a similar issue in mamba recently: for pinned specs and specs from files, conda does not "loosen" the spec. 

But apparently for conda_build_config and other specs in conda_build they do ...

**Comment by chrisburr** [comment]
> To be honest, conda behaves quite differently with regards to this loosen spec. I had a similar issue in mamba recently: for pinned specs and specs from files, conda does not "loosen" the spec. But apparently for conda_build_config and other specs in conda_build they do ...

Delightful!

Given how central openssl is I'm inclined to advocate for the fix to be applied in mamba/boa as I fear it would cause a mess if `1.1.12` or similar was ever released.

**Comment by wolfv** [comment]
ok, then I'll take care of that.

**Comment by wolfv** [comment]
I think this is fixed now, haven't seen this come up in a while :)

**Comment by xhochy** [comment]
I still get this with `boa=0.6.2` in https://github.com/conda-forge/tensorflow-feedstock/pull/131

**Comment by madhur-tandon** [comment]
I am unable to produce this locally. Maybe this has been fixed already?
Also linking logs to where we tried to reproduce this on `xtensor-feedstock`: https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=386176&view=logs&j=656edd35-690f-5c53-9ba3-09c10d0bea97&t=e5c8ab1d-8ff9-5cae-b332-e15ae582ed2d&l=1182

We can see `openssl 1.1.1l h7f98852_0 conda-forge/linux-64 Cached` in the transaction.

**Comment by wolfv** [comment]
@chrisburr and I just chatted and he still sees this error. However, this might only happen when a recipe has multiple outputs (such as the https://github.com/conda-forge/python-feedstock or https://github.com/conda-forge/tensorflow-feedstock).

@madhur-tandon maybe you could adapt the xtensor feedstock to have two outputs and see if that would reproduce the issue?
