### ISSUE TITLE
conda mambabuild failing with "KeyError: Dist" again

### ISSUE THREAD

**Issue by mparry** [mamba-org/boa#165]
I think the problem discussed in #88, #103 and #104 may have reappeared.

> boa                       0.6.0            py37h03978a9_0
> conda                     4.10.3                   pypi_0
> conda-build               3.21.4           py37haa95532_0
> mamba                     0.15.0                   pypi_0
> python                    3.7.10               h6244533_0

> Traceback (most recent call last):
>   File "C:\Miniconda\Scripts\conda-mambabuild-script.py", line 10, in <module>
>     sys.exit(main())
>   File "C:\Miniconda\lib\site-packages\boa\cli\mambabuild.py", line 142, in main
>     call_conda_build(action, config)
>   File "C:\Miniconda\lib\site-packages\boa\cli\mambabuild.py", line 127, in call_conda_build
>     **kwargs,
>   File "C:\Miniconda\lib\site-packages\conda_build\api.py", line 195, in build
>     variants=variants
>   File "C:\Miniconda\lib\site-packages\conda_build\build.py", line 3079, in build_tree
>     test(pkg, config=metadata.config.copy(), stats=stats)
>   File "C:\Miniconda\lib\site-packages\conda_build\build.py", line 2871, in test
>     is_conda=metadata.name() == 'conda')
>   File "C:\Miniconda\lib\site-packages\conda_build\environ.py", line 907, in create_env
>     display_actions(actions, index)
>   File "C:\Miniconda\lib\site-packages\conda\exports.py", line 236, in display_actions
>     actions['LINK'] = [index[d] for d in actions['LINK']]
>   File "C:\Miniconda\lib\site-packages\conda\exports.py", line 236, in <listcomp>
>     actions['LINK'] = [index[d] for d in actions['LINK']]
> KeyError: Dist(channel='file://c:/workspace/XXX_master/conda-bld', dist_name='xxx-2.55.0+master.0.7ad9d1-py_0', name='xxx', fmt='.tar.bz2', version='2.55.0+master.0.7ad9d1', build_string='py_0', build_number=0, base_url=None, platform=None)

Things I would note are:

- It seems like this may be Windows-specific, or at least it seemed to still work on the parallel Linux build that happens in our Jenkins setup.
- It's a `noarch` build.
- As you can see in the output, we tell conda-build to output under a local subdirectory, via the `CONDA_BLD_PATH` env var.

Let me know if there's anything else I can provide.

(Side note: I think the `pypi` versions reported there are an artifact of the environment having been created with micromamba?)

**Comment by wolfv** [comment]
Sorry for the bug! Indeed we just merged a new implementation of the Channel class that is probably responsible for this regression. For now you could pin to mamba 0.14 and boa 0.5 until this is fixed

**Comment by wolfv** [comment]
@afranchuk maybe you've got some insight here

**Comment by afranchuk** [comment]
More specifically, the semantics of channel specifications has changed, so there may be remaining mismatch within consuming implementations. It's not immediately clear to me (mostly due to unfamiliarity with `boa`) how that is interacting with the conda api calls, but I'll read through the source.

**Comment by afranchuk** [comment]
The only thing I see probably incorrect is https://github.com/mamba-org/boa/blob/defd5fa66cd6e7c7661c480a48ce63c13c842011/boa/core/solver.py#L55-L60.

Two things that stand out: you seem to want the url without credentials, but `c["url"]` has credentials (`c["channel"].url(with_credentials=False)` would do the trick I think), and the final `split_anaconda_token(remove_auth(x)[0]` is exactly what was the problem in the mamba index command: `remove_auth` does not correctly parse windows uris. See https://github.com/mamba-org/mamba/blob/master/mamba/utils.py#L309-L315.

Also note that since that should be a url without credentials, maybe the `remove_auth`/`split_anaconda_token` isn't necessary? Technically the `split_anaconda_token` may be, but `remove_auth` certainly shouldn't be needed.

**Comment by traversaro** [comment]
I probably am experience the same problem in https://github.com/robotology/robotology-superbuild/issues/822 when a dependency exist just in the local channel. Interestingly, for me the issue only occures on Windows.

**Comment by wolfv** [comment]
I'll fix it later today. Sorry folks!

**Comment by traversaro** [comment]
> 
> 
> I'll fix it later today. Sorry folks!

No hurries, I'll try to pin mamba and boa.

**Comment by wolfv** [comment]
@afranchuk any chance you know how to fix this?

on Windows, the local channel coming from mamba seems to have `file://c/mychannel/...` format, or `file://c:/mychannel` -- that's why there is the key error.

Gotta investigate it a bit more tomorrow, but should be fixable :)

**Comment by afranchuk** [comment]
Well yeah, it's the same workaround as I linked above with explanation, though I linked it based on `master` so now the link is not the right lines.

It's this: https://github.com/mamba-org/mamba/blob/8812acb77857546e3e081abcd9a8a4540f12cc96/mamba/utils.py#L330-L336

**Comment by afranchuk** [comment]
But also as I said, you could probably do without calling `remove_auth` entirely.

**Comment by wolfv** [comment]
ok, this looks to be the difference -- will fix it now 

<img width="447" alt="Screenshot 2021-07-15 at 08 09 36" src="https://user-images.githubusercontent.com/885054/125737668-28bfdd76-2b87-431b-8fef-0b537fe2a280.png">

**Comment by mparry** [comment]
I think this is fixed now? Do we need both mamba 0.15.1 and boa 0.6.1 or just one of those?

**Comment by wolfv** [comment]
both will have to be at the latest version, although there is still an issue in the tests on master which I am fixing now.

**Comment by mparry** [comment]
Unfortunately that still fails, though the exception has changed a bit:

```
KeyError: Dist(channel='file://c/workspace/XXX_master/conda-bld', dist_name='xxx-2.55.0+master.46c40d-py_0', name='xxx', fmt='.tar.bz2', version='2.55.0+master.46c40d', build_string='py_0', build_number=0, base_url=None, platform=None)
```

(Note that the colon in `c:` has disappeared now)

**Comment by wolfv** [comment]
yes, one more update to go :) sorry. 

the proper URL form on Windows is `file:///c:/...` (note the triple slashes).

Will cut another mamba release right now, then it should be fixed.

**Comment by wolfv** [comment]
it should be fixed now with mamba 0.15.2 and boa 0.6.2

**Comment by traversaro** [comment]
Indeed, everything works fine for the robotology channel generations, and we removed all the pinnings in https://github.com/robotology/robotology-superbuild/pull/834 .

**Comment by capn-freako** [comment]
Is this tickling the same thing?

```
KeyError: Dist(channel='defaults', dist_name='tzdata-2023c-h04d1e81_0', name='tzdata', fmt='.conda', version='2023c', build_string='h04d1e81_0', build_number=0, base_url=None, platform=None)
```

I'm getting this under Windows 10 WSL2 _Ubuntu_.

```
(pybert)
dbanas@Dell-XPS-15:~
$ conda info

     active environment : pybert
    active env location : /home/dbanas/miniconda3/envs/pybert
            shell level : 2
       user config file : /home/dbanas/.condarc
 populated config files : /home/dbanas/.condarc
          conda version : 23.3.0
    conda-build version : 3.23.3
         python version : 3.10.9.final.0
       virtual packages : __archspec=1=x86_64
                          __cuda=12.0=0
                          __glibc=2.35=0
                          __linux=5.15.90.1=0
                          __unix=0=0
       base environment : /home/dbanas/miniconda3  (writable)
      conda av data dir : /home/dbanas/miniconda3/etc/conda
  conda av metadata url : None
           channel URLs : https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /home/dbanas/miniconda3/pkgs
                          /home/dbanas/.conda/pkgs
       envs directories : /home/dbanas/miniconda3/envs
                          /home/dbanas/.conda/envs
               platform : linux-64
             user-agent : conda/23.3.0 requests/2.28.1 CPython/3.10.9 Linux/5.15.90.1-microsoft-standard-WSL2 ubuntu/22.04.1 glibc/2.35 solver/libmamba conda-libmamba-solver/22.8.1 libmambapy/1.3.1
                UID:GID : 1000:1000
             netrc file : None
           offline mode : False
```
